#!/usr/bin/env python3
"""
Prepare the DINO-Unity-21 project for a HoloLens 2 UWP build.

This script automates the project adjustments described in the project notes:

* Switch Unity to Universal Windows Platform (WSAPlayer).
* Configure the UWP target for HoloLens, ARM64, and D3D Project output.
* Enable the Unity-exposed UWP capabilities needed by the project.
* Build a Visual Studio solution when requested.
* Patch Package.appxmanifest with the Research Mode restricted capability.
* Verify that the generated .sln contains Release|ARM64.

The default subcommand is "audit", which performs read-only checks. Use the
explicit subcommands below when you actually want the script to change files:

    python configure_hl2_uwp_build.py configure --unity "C:\\...\\Unity.exe"
    python configure_hl2_uwp_build.py build --unity "C:\\...\\Unity.exe"
    python configure_hl2_uwp_build.py patch-manifest --build-dir ".\\Builds\\DINO-Unity21-UWP"
    python configure_hl2_uwp_build.py all --unity "C:\\...\\Unity.exe"
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable
import xml.etree.ElementTree as ET


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_PROJECT_DIR = SCRIPT_DIR / "DINO-Unity-21"
DEFAULT_BUILD_DIR = SCRIPT_DIR / "Builds" / "DINO-Unity21-UWP"
DEFAULT_LOG_DIR = SCRIPT_DIR / "Logs"

GENERATED_EDITOR_SCRIPT = "Hl2UwpBuildAutomation.Generated.cs"
GENERATED_MARKER = "Generated by configure_hl2_uwp_build.py"

APPX_NS = "http://schemas.microsoft.com/appx/manifest/foundation/windows10"
MP_NS = "http://schemas.microsoft.com/appx/2014/phone/manifest"
UAP_NS = "http://schemas.microsoft.com/appx/manifest/uap/windows10"
UAP2_NS = "http://schemas.microsoft.com/appx/manifest/uap/windows10/2"
UAP3_NS = "http://schemas.microsoft.com/appx/manifest/uap/windows10/3"
UAP4_NS = "http://schemas.microsoft.com/appx/manifest/uap/windows10/4"
IOT_NS = "http://schemas.microsoft.com/appx/manifest/iot/windows10"
MOBILE_NS = "http://schemas.microsoft.com/appx/manifest/mobile/windows10"
RESCAP_NS = "http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"

IGNORABLE_NAMESPACES = ["uap", "uap2", "uap3", "uap4", "mp", "mobile", "iot", "rescap"]

REQUIRED_CAPABILITIES = [
    ("rescap", "Capability", "perceptionSensorsExperimental"),
    ("default", "Capability", "internetClient"),
    ("default", "Capability", "internetClientServer"),
    ("default", "Capability", "privateNetworkClientServer"),
    ("uap2", "Capability", "spatialPerception"),
    ("default", "DeviceCapability", "webcam"),
]

NAMESPACE_BY_PREFIX = {
    "default": APPX_NS,
    "mp": MP_NS,
    "uap": UAP_NS,
    "uap2": UAP2_NS,
    "uap3": UAP3_NS,
    "uap4": UAP4_NS,
    "iot": IOT_NS,
    "mobile": MOBILE_NS,
    "rescap": RESCAP_NS,
}


UNITY_EDITOR_AUTOMATION = r"""/*
 * Generated by configure_hl2_uwp_build.py.
 * The Python script recreates this file before invoking Unity and removes it
 * afterwards unless --keep-editor-script is supplied.
 */
#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;

public static class Hl2UwpBuildAutomation
{
    private const string BuildDirArg = "--hl2-build-dir";

    public static void ConfigureOnly()
    {
        ConfigureUwpHoloLensSettings(GetBuildDirFromArgs(required: false));
    }

    public static void BuildUwp()
    {
        string buildDir = GetBuildDirFromArgs(required: true);
        ConfigureUwpHoloLensSettings(buildDir);
        BuildPlayer(buildDir);
    }

    private static string GetBuildDirFromArgs(bool required)
    {
        string[] args = Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length - 1; i++)
        {
            if (args[i] == BuildDirArg)
            {
                return Path.GetFullPath(args[i + 1]);
            }
        }

        if (required)
        {
            throw new ArgumentException("Missing " + BuildDirArg + " command-line argument.");
        }

        return null;
    }

    private static void ConfigureUwpHoloLensSettings(string buildDir)
    {
        const BuildTarget target = BuildTarget.WSAPlayer;
        const BuildTargetGroup group = BuildTargetGroup.WSA;

        // This is the programmatic equivalent of selecting Universal Windows
        // Platform in Unity Build Settings before building.
        if (EditorUserBuildSettings.activeBuildTarget != target)
        {
            bool switched = EditorUserBuildSettings.SwitchActiveBuildTarget(group, target);
            if (!switched)
            {
                throw new InvalidOperationException("Could not switch active build target to UWP/WSAPlayer.");
            }
        }

        // Match the requested Unity Build Settings:
        // Target Device = HoloLens, Architecture = ARM64, Build Type = D3D Project.
#pragma warning disable 0618
        EditorUserBuildSettings.wsaSubtarget = WSASubtarget.HoloLens;
#pragma warning restore 0618
        EditorUserBuildSettings.wsaArchitecture = "ARM64";
        EditorUserBuildSettings.wsaUWPBuildType = WSAUWPBuildType.D3D;
        EditorUserBuildSettings.development = false;
        EditorUserBuildSettings.allowDebugging = false;
        EditorUserBuildSettings.buildScriptsOnly = false;

        if (!string.IsNullOrEmpty(buildDir))
        {
            Directory.CreateDirectory(buildDir);
            EditorUserBuildSettings.SetBuildLocation(target, buildDir);
        }

        // HoloLens 2 ARM64 UWP builds should use IL2CPP.
        PlayerSettings.SetScriptingBackend(group, ScriptingImplementation.IL2CPP);

        ConfigureTargetFamilies();
        ConfigureCapabilities();

        AssetDatabase.SaveAssets();
        Debug.Log("[HL2-UWP] Configured UWP target: HoloLens, ARM64, D3D Project, Release-style build.");
    }

    private static void ConfigureTargetFamilies()
    {
        // Keep the generated manifest focused on HoloLens devices.
        foreach (PlayerSettings.WSATargetFamily family in Enum.GetValues(typeof(PlayerSettings.WSATargetFamily)))
        {
            PlayerSettings.WSA.SetTargetDeviceFamily(family, family == PlayerSettings.WSATargetFamily.Holographic);
        }
    }

    private static void ConfigureCapabilities()
    {
        // Unity can write these ordinary UWP capabilities during the first
        // UWP build. The restricted Research Mode capability is patched into
        // Package.appxmanifest by Python after the Visual Studio project exists.
        PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.InternetClient, true);
        PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.InternetClientServer, true);
        PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.PrivateNetworkClientServer, true);
        PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.SpatialPerception, true);
        PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.WebCam, true);
    }

    private static void BuildPlayer(string buildDir)
    {
        string[] scenes = EditorBuildSettings.scenes
            .Where(scene => scene.enabled)
            .Select(scene => scene.path)
            .ToArray();

        if (scenes.Length == 0)
        {
            throw new InvalidOperationException("No enabled scenes were found in EditorBuildSettings.");
        }

        BuildPlayerOptions options = new BuildPlayerOptions
        {
            scenes = scenes,
            locationPathName = buildDir,
            target = BuildTarget.WSAPlayer,
            targetGroup = BuildTargetGroup.WSA,
            options = BuildOptions.None
        };

        BuildReport report = BuildPipeline.BuildPlayer(options);
        if (report.summary.result != BuildResult.Succeeded)
        {
            throw new InvalidOperationException("Unity UWP build failed: " + report.summary.result);
        }

        Debug.Log("[HL2-UWP] Unity generated Visual Studio project at: " + buildDir);
    }
}
#endif
"""


@dataclass(frozen=True)
class ManifestPatchResult:
    path: Path
    changed: bool
    backup_path: Path | None
    messages: list[str]


def info(message: str) -> None:
    print(f"[INFO] {message}")


def warn(message: str) -> None:
    print(f"[WARN] {message}")


def error(message: str) -> None:
    print(f"[ERROR] {message}", file=sys.stderr)


def resolve_path(path: str | Path) -> Path:
    return Path(path).expanduser().resolve()


def ensure_unity_project(project_dir: Path) -> None:
    project_settings = project_dir / "ProjectSettings" / "ProjectSettings.asset"
    assets_dir = project_dir / "Assets"
    if not project_settings.is_file() or not assets_dir.is_dir():
        raise FileNotFoundError(f"{project_dir} does not look like a Unity project.")


def read_unity_version(project_dir: Path) -> str | None:
    version_file = project_dir / "ProjectSettings" / "ProjectVersion.txt"
    if not version_file.is_file():
        return None

    for line in version_file.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("m_EditorVersion:"):
            return line.split(":", 1)[1].strip()
    return None


def find_unity_exe(project_dir: Path, explicit_unity: str | None) -> Path:
    candidates: list[Path] = []

    if explicit_unity:
        candidates.append(resolve_path(explicit_unity))

    env_unity = os.environ.get("UNITY_EXE")
    if env_unity:
        candidates.append(resolve_path(env_unity))

    version = read_unity_version(project_dir)
    if version:
        candidates.extend(
            [
                Path("C:/Program Files/Unity/Hub/Editor") / version / "Editor/Unity.exe",
                Path("C:/Program Files/Unity") / version / "Editor/Unity.exe",
            ]
        )

    candidates.extend(
        [
            Path("C:/Program Files/Unity/Editor/Unity.exe"),
            Path("C:/Program Files/Unity Hub/Unity Hub.exe"),
        ]
    )

    for candidate in candidates:
        if candidate.is_file() and candidate.name.lower() == "unity.exe":
            return candidate

    raise FileNotFoundError(
        "Could not find Unity.exe. Pass --unity explicitly or set UNITY_EXE. "
        f"Project Unity version: {version or 'unknown'}."
    )


def editor_script_path(project_dir: Path) -> Path:
    return project_dir / "Assets" / "Editor" / GENERATED_EDITOR_SCRIPT


def write_editor_automation(project_dir: Path) -> Path:
    target = editor_script_path(project_dir)
    target.parent.mkdir(parents=True, exist_ok=True)

    if target.exists():
        existing = target.read_text(encoding="utf-8", errors="replace")
        if GENERATED_MARKER not in existing:
            raise FileExistsError(
                f"Refusing to overwrite non-generated editor script: {target}"
            )

    target.write_text(UNITY_EDITOR_AUTOMATION, encoding="utf-8", newline="\n")
    return target


def cleanup_editor_automation(project_dir: Path, keep: bool) -> None:
    if keep:
        return

    target = editor_script_path(project_dir)
    for candidate in [target, target.with_suffix(target.suffix + ".meta")]:
        if not candidate.exists():
            continue
        if candidate == target:
            text = candidate.read_text(encoding="utf-8", errors="replace")
            if GENERATED_MARKER not in text:
                warn(f"Leaving non-generated editor script untouched: {candidate}")
                continue
        candidate.unlink()


def run_unity_method(
    *,
    unity_exe: Path,
    project_dir: Path,
    build_dir: Path,
    method: str,
    log_file: Path,
    keep_editor_script: bool,
    nographics: bool,
) -> None:
    ensure_unity_project(project_dir)
    write_editor_automation(project_dir)
    log_file.parent.mkdir(parents=True, exist_ok=True)

    command = [
        str(unity_exe),
        "-batchmode",
        "-quit",
        "-projectPath",
        str(project_dir),
        "-logFile",
        str(log_file),
        "-executeMethod",
        method,
        "--hl2-build-dir",
        str(build_dir),
    ]
    if nographics:
        command.insert(2, "-nographics")

    info("Launching Unity in batch mode.")
    info("Unity log: " + str(log_file))

    try:
        completed = subprocess.run(command, check=False)
        if completed.returncode != 0:
            raise RuntimeError(
                f"Unity exited with code {completed.returncode}. Check log: {log_file}"
            )
    finally:
        cleanup_editor_automation(project_dir, keep_editor_script)


def register_manifest_namespaces() -> None:
    ET.register_namespace("", APPX_NS)
    ET.register_namespace("mp", MP_NS)
    ET.register_namespace("uap", UAP_NS)
    ET.register_namespace("uap2", UAP2_NS)
    ET.register_namespace("uap3", UAP3_NS)
    ET.register_namespace("uap4", UAP4_NS)
    ET.register_namespace("iot", IOT_NS)
    ET.register_namespace("mobile", MOBILE_NS)
    ET.register_namespace("rescap", RESCAP_NS)


def namespaced_tag(prefix: str, local_name: str) -> str:
    return f"{{{NAMESPACE_BY_PREFIX[prefix]}}}{local_name}"


def find_manifest(build_dir: Path, explicit_manifest: str | None) -> Path:
    if explicit_manifest:
        manifest = resolve_path(explicit_manifest)
        if not manifest.is_file():
            raise FileNotFoundError(f"Package.appxmanifest was not found: {manifest}")
        return manifest

    candidates = sorted(build_dir.rglob("Package.appxmanifest")) if build_dir.exists() else []
    if len(candidates) == 1:
        return candidates[0]
    if not candidates:
        raise FileNotFoundError(
            f"No Package.appxmanifest found under {build_dir}. Build the UWP project first "
            "or pass --manifest."
        )

    formatted = "\n  ".join(str(path) for path in candidates)
    raise RuntimeError(
        "Multiple Package.appxmanifest files were found. Pass --manifest explicitly:\n  "
        + formatted
    )


def find_solution(build_dir: Path, explicit_solution: str | None = None) -> Path | None:
    if explicit_solution:
        solution = resolve_path(explicit_solution)
        if not solution.is_file():
            raise FileNotFoundError(f"Solution file was not found: {solution}")
        return solution

    candidates = sorted(build_dir.rglob("*.sln")) if build_dir.exists() else []
    if len(candidates) == 1:
        return candidates[0]
    return None


def ensure_ignorable_namespaces(root: ET.Element) -> bool:
    existing = root.attrib.get("IgnorableNamespaces", "")
    tokens = [token for token in existing.split() if token]
    changed = False

    for required in IGNORABLE_NAMESPACES:
        if required not in tokens:
            tokens.append(required)
            changed = True

    ordered = [token for token in IGNORABLE_NAMESPACES if token in tokens]
    ordered.extend(token for token in tokens if token not in ordered)
    new_value = " ".join(ordered)
    if new_value != existing:
        root.set("IgnorableNamespaces", new_value)
        changed = True

    return changed


def find_or_create_capabilities(root: ET.Element) -> tuple[ET.Element, bool]:
    capabilities = root.find(namespaced_tag("default", "Capabilities"))
    if capabilities is not None:
        return capabilities, False

    capabilities = ET.Element(namespaced_tag("default", "Capabilities"))
    root.append(capabilities)
    return capabilities, True


def capability_exists(capabilities: ET.Element, prefix: str, local_name: str, name: str) -> bool:
    tag = namespaced_tag(prefix, local_name)
    return any(child.tag == tag and child.attrib.get("Name") == name for child in capabilities)


def add_missing_capabilities(capabilities: ET.Element) -> list[str]:
    added: list[str] = []
    for prefix, local_name, capability_name in REQUIRED_CAPABILITIES:
        if capability_exists(capabilities, prefix, local_name, capability_name):
            continue

        element = ET.Element(namespaced_tag(prefix, local_name))
        element.set("Name", capability_name)
        capabilities.append(element)
        display_prefix = "" if prefix == "default" else prefix + ":"
        added.append(f"{display_prefix}{local_name} Name=\"{capability_name}\"")

    return added


def patch_manifest(manifest_path: Path, *, create_backup: bool) -> ManifestPatchResult:
    register_manifest_namespaces()
    messages: list[str] = []

    parser = ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))
    tree = ET.parse(manifest_path, parser=parser)
    root = tree.getroot()

    changed = ensure_ignorable_namespaces(root)
    if changed:
        messages.append("Updated IgnorableNamespaces to include rescap and UWP prefixes.")

    capabilities, created_capabilities = find_or_create_capabilities(root)
    if created_capabilities:
        changed = True
        messages.append("Created missing <Capabilities> element.")

    added = add_missing_capabilities(capabilities)
    if added:
        changed = True
        messages.extend("Added " + item + "." for item in added)

    if not changed:
        return ManifestPatchResult(manifest_path, False, None, ["Manifest already contains required entries."])

    backup_path = None
    if create_backup:
        stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup_path = manifest_path.with_suffix(manifest_path.suffix + f".bak-{stamp}")
        shutil.copy2(manifest_path, backup_path)

    if hasattr(ET, "indent"):
        ET.indent(tree, space="  ")
    tree.write(manifest_path, encoding="utf-8", xml_declaration=True)

    return ManifestPatchResult(manifest_path, True, backup_path, messages)


def read_text_if_exists(path: Path) -> str:
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def audit_manifest(manifest_path: Path) -> list[str]:
    register_manifest_namespaces()
    parser = ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))
    tree = ET.parse(manifest_path, parser=parser)
    root = tree.getroot()
    capabilities = root.find(namespaced_tag("default", "Capabilities"))

    lines: list[str] = [f"Manifest: {manifest_path}"]
    ignorables = set(root.attrib.get("IgnorableNamespaces", "").split())
    missing_ignorables = [item for item in IGNORABLE_NAMESPACES if item not in ignorables]
    if missing_ignorables:
        lines.append("  Missing IgnorableNamespaces tokens: " + ", ".join(missing_ignorables))
    else:
        lines.append("  IgnorableNamespaces includes required tokens.")

    if capabilities is None:
        lines.append("  Missing <Capabilities> element.")
        return lines

    for prefix, local_name, capability_name in REQUIRED_CAPABILITIES:
        status = "ok" if capability_exists(capabilities, prefix, local_name, capability_name) else "missing"
        display_prefix = "" if prefix == "default" else prefix + ":"
        lines.append(f"  {status}: {display_prefix}{local_name} Name=\"{capability_name}\"")

    return lines


def audit_solution(solution_path: Path) -> list[str]:
    text = read_text_if_exists(solution_path)
    lines = [f"Solution: {solution_path}"]
    if "Release|ARM64" in text:
        lines.append("  ok: solution contains Release|ARM64.")
    else:
        lines.append("  missing: solution does not contain Release|ARM64.")

    if ".Deploy.0 = Release|ARM64" in text:
        lines.append("  ok: Release|ARM64 deploy mapping exists.")
    else:
        lines.append("  note: Release|ARM64 deploy mapping was not found; verify in Visual Studio before deploy.")

    return lines


def audit_project_settings(project_dir: Path) -> list[str]:
    project_settings = project_dir / "ProjectSettings" / "ProjectSettings.asset"
    text = read_text_if_exists(project_settings)
    lines = [f"Project: {project_dir}"]
    version = read_unity_version(project_dir)
    lines.append(f"  Unity version: {version or 'unknown'}")

    checks = {
        "targetDevice: 2": "Target Device appears to be HoloLens.",
        "Holographic: True": "Holographic target device family is enabled.",
        "InternetClient: True": "internetClient capability is enabled in Unity settings.",
        "InternetClientServer: True": "internetClientServer capability is enabled in Unity settings.",
        "PrivateNetworkClientServer: True": "privateNetworkClientServer capability is enabled in Unity settings.",
        "SpatialPerception: True": "spatialPerception capability is enabled in Unity settings.",
        "WebCam: True": "webcam capability is enabled in Unity settings.",
    }
    for needle, message in checks.items():
        status = "ok" if needle in text else "missing"
        lines.append(f"  {status}: {message}")

    return lines


def print_lines(lines: Iterable[str]) -> None:
    for line in lines:
        print(line)


def command_audit(args: argparse.Namespace) -> int:
    project_dir = resolve_path(args.project)
    build_dir = resolve_path(args.build_dir)
    ensure_unity_project(project_dir)

    print_lines(audit_project_settings(project_dir))

    try:
        manifest = find_manifest(build_dir, args.manifest)
    except FileNotFoundError as exc:
        warn(str(exc))
    except RuntimeError as exc:
        warn(str(exc))
    else:
        print_lines(audit_manifest(manifest))

    try:
        solution = find_solution(build_dir, args.solution)
    except FileNotFoundError as exc:
        warn(str(exc))
    else:
        if solution is None:
            warn(f"No .sln file found under {build_dir}.")
        else:
            print_lines(audit_solution(solution))

    return 0


def command_configure(args: argparse.Namespace) -> int:
    project_dir = resolve_path(args.project)
    build_dir = resolve_path(args.build_dir)
    unity_exe = find_unity_exe(project_dir, args.unity)
    log_file = resolve_path(args.log_file) if args.log_file else DEFAULT_LOG_DIR / "unity-configure-hl2-uwp.log"

    run_unity_method(
        unity_exe=unity_exe,
        project_dir=project_dir,
        build_dir=build_dir,
        method="Hl2UwpBuildAutomation.ConfigureOnly",
        log_file=log_file,
        keep_editor_script=args.keep_editor_script,
        nographics=not args.no_nographics,
    )
    return 0


def command_build(args: argparse.Namespace) -> int:
    project_dir = resolve_path(args.project)
    build_dir = resolve_path(args.build_dir)
    unity_exe = find_unity_exe(project_dir, args.unity)
    log_file = resolve_path(args.log_file) if args.log_file else DEFAULT_LOG_DIR / "unity-build-hl2-uwp.log"

    run_unity_method(
        unity_exe=unity_exe,
        project_dir=project_dir,
        build_dir=build_dir,
        method="Hl2UwpBuildAutomation.BuildUwp",
        log_file=log_file,
        keep_editor_script=args.keep_editor_script,
        nographics=not args.no_nographics,
    )

    solution = find_solution(build_dir, args.solution)
    if solution is None:
        raise FileNotFoundError(f"Unity build completed, but no .sln was found under {build_dir}.")

    print_lines(audit_solution(solution))
    if args.open_sln:
        os.startfile(solution)  # type: ignore[attr-defined]
    return 0


def command_patch_manifest(args: argparse.Namespace) -> int:
    build_dir = resolve_path(args.build_dir)
    manifest = find_manifest(build_dir, args.manifest)
    result = patch_manifest(manifest, create_backup=not args.no_backup)

    if result.changed:
        info("Patched manifest: " + str(result.path))
        if result.backup_path:
            info("Backup: " + str(result.backup_path))
    else:
        info("No manifest changes were needed: " + str(result.path))

    print_lines("  " + message for message in result.messages)

    solution = find_solution(build_dir, args.solution)
    if solution is None:
        warn(f"No .sln file found under {build_dir}; cannot audit Release|ARM64.")
    else:
        print_lines(audit_solution(solution))
        if "Release|ARM64" not in read_text_if_exists(solution):
            raise RuntimeError("Generated solution does not contain Release|ARM64.")

    if args.open_sln and solution is not None:
        os.startfile(solution)  # type: ignore[attr-defined]
    return 0


def command_all(args: argparse.Namespace) -> int:
    open_sln = args.open_sln
    args.open_sln = False
    command_build(args)
    args.open_sln = open_sln
    command_patch_manifest(args)
    return 0


def add_common_paths(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--project", default=str(DEFAULT_PROJECT_DIR), help="Unity project directory.")
    parser.add_argument("--build-dir", default=str(DEFAULT_BUILD_DIR), help="UWP Visual Studio output directory.")
    parser.add_argument("--manifest", help="Explicit Package.appxmanifest path.")
    parser.add_argument("--solution", help="Explicit .sln path.")


def add_unity_options(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--unity", help="Path to Unity.exe. If omitted, UNITY_EXE or ProjectVersion.txt is used.")
    parser.add_argument("--log-file", help="Unity batchmode log file path.")
    parser.add_argument(
        "--keep-editor-script",
        action="store_true",
        help="Leave the generated Unity editor automation script in Assets/Editor for debugging.",
    )
    parser.add_argument(
        "--no-nographics",
        action="store_true",
        help="Do not pass -nographics to Unity batchmode.",
    )


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Configure and patch the HL2 DINO Unity UWP build.")
    subparsers = parser.add_subparsers(dest="command")

    audit = subparsers.add_parser("audit", help="Read-only project/build output checks.")
    add_common_paths(audit)
    audit.set_defaults(func=command_audit)

    configure = subparsers.add_parser("configure", help="Use Unity to configure UWP/HoloLens/ARM64/D3D settings.")
    add_common_paths(configure)
    add_unity_options(configure)
    configure.set_defaults(func=command_configure)

    build = subparsers.add_parser("build", help="Configure settings and generate the UWP Visual Studio project.")
    add_common_paths(build)
    add_unity_options(build)
    build.add_argument("--open-sln", action="store_true", help="Open the generated .sln after a successful build.")
    build.set_defaults(func=command_build)

    patch = subparsers.add_parser("patch-manifest", help="Patch Package.appxmanifest after Unity export.")
    add_common_paths(patch)
    patch.add_argument("--no-backup", action="store_true", help="Do not create a timestamped manifest backup.")
    patch.add_argument("--open-sln", action="store_true", help="Open the generated .sln after patching.")
    patch.set_defaults(func=command_patch_manifest)

    all_cmd = subparsers.add_parser("all", help="Build, patch manifest, and audit the generated solution.")
    add_common_paths(all_cmd)
    add_unity_options(all_cmd)
    all_cmd.add_argument("--no-backup", action="store_true", help="Do not create a timestamped manifest backup.")
    all_cmd.add_argument("--open-sln", action="store_true", help="Open the generated .sln after patching.")
    all_cmd.set_defaults(func=command_all)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_arg_parser()
    args_list = list(sys.argv[1:] if argv is None else argv)

    # Default to read-only audit mode so that accidentally invoking the script
    # never starts Unity or mutates a generated Visual Studio project.
    if not args_list:
        args_list = ["audit"]

    args = parser.parse_args(args_list)
    try:
        return args.func(args)
    except Exception as exc:  # noqa: BLE001 - command-line tool should report any failure cleanly.
        error(str(exc))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
